import { FileTypes } from '@shared';
import { Request } from 'express';

type cbFileName = (file: Express.Multer.File, req?: Request) => string;

export interface UploaderOptions {
    destination?: string;
    allowedFileTypes?: FileTypes[];
    allowedFileExtensions?: string[];
    originalName?: boolean;
    maxFileSize?: number | string;

    /**
     * @param fileName: optional, if not provided, the file name will be generated by default
     * @description fileName will be ignored if `originalName = true`
     * @example: 'file', 'file.jpg' # Allow missing extension filename
     * @example: (file) => `prefix-${file.originalname}`
     */
    fileName?: string | cbFileName;

    /**
     * @param fileName: optional, default `true`
     * Overwrite file if exists or throw error
     */
    overwrite?: boolean;

    /**
     * @param multiple - optional, default `false`
     */
    multiple?: boolean;

    /**
     * @param maxCount: optional number defining the maximum number of files to accept, default `Infinity`
     */
    maxCount?: number;
}
